In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Create a DataFrame with simpler, flat column names
records = [
    {
        "participant": "Fares",
        "abbreviation": "A",
        "origin": "urban",
        "q_words": 4,
        "q_1": 12,
        "q_2": 6,
        "q_3": 8,
        "q_4": 28,
        "q_5": 6,
        "q_6": 12,
        "q_7": 10,
        "q_8": 18,
        "q_9": 8,
        "?_words": 7,
        "?_1": 0,
        "?_2": 0,
        "?_3": 0,
        "?_4": 0,
        "?_5": 0,
        "?_6": 2,
        "?_7": 0,
        "?_8": 0,
        "?_9": 0,
    },
    {
        "participant": "Mahmoud",
        "origin": "rural",
        "abbreviation": "B",
        "q_words": 10,
        "q_1": 4,
        "q_2": 0,
        "q_3": 2,
        "q_4": 3,
        "q_5": 2,
        "q_6": 3,
        "?_words": 0,
        "?_1": 0,
        "?_2": 0,
        "?_3": 0,
        "?_4": 0,
        "?_5": 0,
        "?_6": 0,
    },
    {
        "participant": "Ola",
        "origin": "rural",
        "abbreviation": "C",
        "q_words": 10,
        "q_1": 1,
        "q_2": 1,
        "q_3": 0,
        "q_4": 0,
        "q_5": 0,
        "q_6": 0,
        "?_words": 1,
        "?_1": 3,
        "?_2": 1,
        "?_3": 0,
        "?_4": 1,
        "?_5": 0,
        "?_6": 4,
    },
    {
        "participant": "Rawan",
        "origin": "rural",
        "abbreviation": "D",
        "q_words": 11,
        "q_1": 6,
        "q_2": 4,
        "q_3": 2,
        "q_4": 7,
        "q_5": 4,
        "q_6": 7,
        "?_words": 0,
        "?_1": 0,
        "?_2": 0,
        "?_3": 0,
        "?_4": 0,
        "?_5": 0,
        "?_6": 0,
    },
    {
        "participant": "Taymaa",
        "origin": "urban",
        "abbreviation": "E",
        "q_words": 5,
        "q_1": 2,
        "q_2": 0,
        "q_3": 1,
        "q_4": 3,
        "q_5": 0,
        "q_6": 1,
        "?_words": 6,
        "?_1": 2,
        "?_2": 1,
        "?_3": 2,
        "?_4": 0,
        "?_5": 1,
        "?_6": 3,
    },
    {
        "participant": "Jalil",
        "origin": "urban",
        "abbreviation": "F",
        "q_words": 2,
        "q_1": 1,
        "q_2": 1,
        "q_3": 2,
        "q_4": 2,
        "q_5": 0,
        "q_6": 3,
        "?_words": 9,
        "?_1": 1,
        "?_2": 0,
        "?_3": 0,
        "?_4": 1,
        "?_5": 0,
        "?_6": 0,
    },
    {
        "participant": "Mulham",
        "origin": "rural",
        "abbreviation": "G",
        "q_words": 11,
        "q_1": 5,
        "q_2": 3,
        "q_3": 0,
        "q_4": 2,
        "q_5": 2,
        "q_6": 4,
        "?_words": 0,
        "?_1": 0,
        "?_2": 0,
        "?_3": 0,
        "?_4": 0,
        "?_5": 0,
        "?_6": 0,
    },
    {
        "participant": "Ranim",
        "origin": "urban",
        "abbreviation": "H",
        "q_words": 3,
        "q_1": 3,
        "q_2": 2,
        "q_3": 1,
        "q_4": 1,
        "q_5": 0,
        "q_6": 1,
        "?_words": 8,
        "?_1": 1,
        "?_2": 3,
        "?_3": 2,
        "?_4": 2,
        "?_5": 3,
        "?_6": 6,
    },
]

data = pd.DataFrame(records)

data

,participant,abbreviation,origin,q_words,q_1,q_2,q_3,q_4,q_5,q_6,...,?_words,?_1,?_2,?_3,?_4,?_5,?_6,?_7,?_8,?_9
0,Fares,A,urban,4,12,6,8,28,6,12,...,7,0,0,0,0,0,2,0.0,0.0,0.0
1,Mahmoud,B,rural,10,4,0,2,3,2,3,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,Ola,C,rural,10,1,1,0,0,0,0,...,1,3,1,0,1,0,4,NaN,NaN,NaN
3,Rawan,D,rural,11,6,4,2,7,4,7,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,Taymaa,E,urban,5,2,0,1,3,0,1,...,6,2,1,2,0,1,3,NaN,NaN,NaN
5,Jalil,F,urban,2,1,1,2,2,0,3,...,9,1,0,0,1,0,0,NaN,NaN,NaN
6,Mulham,G,rural,11,5,3,0,2,2,4,...,0,0,0,0,0,0,0,NaN,NaN,NaN
7,Ranim,H,urban,3,3,2,1,1,0,1,...,8,1,3,2,2,3,6,NaN,NaN,NaN

In [3]:
statistics_df = pd.DataFrame(data[["participant", "abbreviation", "origin"]].copy())
 
statistics_df["q_total"] = data.filter(like="q_").sum(axis=1)
statistics_df["?_total"] = data.filter(like="?_").sum(axis=1)
statistics_df["total"] = statistics_df["q_total"] + statistics_df["?_total"]

# sort by origin 
statistics_df.sort_values(by="origin", inplace=True, ignore_index=True)

statistics_df

  participant abbreviation origin  q_total  ?_total  total
0     Mahmoud            B  rural     24.0      0.0   24.0
1         Ola            C  rural     12.0     10.0   22.0
2       Rawan            D  rural     41.0      0.0   41.0
3      Mulham            G  rural     27.0      0.0   27.0
4       Fares            A  urban    112.0      9.0  121.0
5      Taymaa            E  urban     12.0     15.0   27.0
6       Jalil            F  urban     11.0     11.0   22.0
7       Ranim            H  urban     11.0     25.0   36.0

In [4]:
mean = statistics_df["total"].mean()
median = statistics_df["total"].median()
print(f"Mean: {mean}. Median: {median}")

statistics_df

Mean: 40.0. Median: 27.0

  participant abbreviation origin  q_total  ?_total  total
0     Mahmoud            B  rural     24.0      0.0   24.0
1         Ola            C  rural     12.0     10.0   22.0
2       Rawan            D  rural     41.0      0.0   41.0
3      Mulham            G  rural     27.0      0.0   27.0
4       Fares            A  urban    112.0      9.0  121.0
5      Taymaa            E  urban     12.0     15.0   27.0
6       Jalil            F  urban     11.0     11.0   22.0
7       Ranim            H  urban     11.0     25.0   36.0

In [5]:
hypothesis_1 = statistics_df[["abbreviation", "origin", "?_total", "q_total"]].copy()
# rename abbreviation to participant 
hypothesis_1.rename(columns={"abbreviation": "participant"}, inplace=True)
hypothesis_1["phoneme"] = hypothesis_1.apply(
    lambda row: "q" if row["q_total"] > row["?_total"] else "?", axis=1
)
hypothesis_1[["participant", "origin", "phoneme"]]

  participant origin phoneme
0           B  rural       q
1           C  rural       q
2           D  rural       q
3           G  rural       q
4           A  urban       q
5           E  urban       ?
6           F  urban       ?
7           H  urban       ?

In [6]:
# plot hypothesis 1 data using